### ISSUE TITLE
q dependency missing in npm

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#188]
When installing (npm install) it fails: 
module.js:340
    throw err;
          ^
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/fllscoring/localserver.js:4:9
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by poelstra** [comment]
It's present in `package.json`, so this is strange.
Can you copy-paste the full log of everything you typed and what was output from a clone?

**Comment by poelstra** [comment]
Just tried it myself: removing `node_modules`, then `npm install`.
Install finished without complaints, but q is indeed not installed (?!), although it really is in the list of dependencies.

Installing it manually through `npm install q@1.4.1` does work though.

Removing `node_modules/q`, then `npm install` does nothing, but `npm install q` nicely install q 1.4.1.

I'm stumped :-/

**Comment by poelstra** [comment]
Tested with `npm 2.8.3`.
Upgraded npm itself: `npm install -g npm`, got version 3.7.5.

Then `npm install` did install `q` correctly.

Closing this as an npm bug, please upgrade to a later version of Node.JS / npm.
